.TH util 1 "July 2025" "shell-utils" "User Commands"
.SH NAME
util \- A shell-agnostic utility tool for managing scripts
.SH SYNOPSIS
.B util
[\-\-help] [command] [arguments]
.SH DESCRIPTION
.B util
is a shell-agnostic utility tool designed to make your scripts accessible everywhere using the `util` command.

The command accepts a name argument, representing the script to execute from `$HOME/.config/util/scripts`. Any additional arguments are seamlessly passed to the specified script.

Setup scripts for third-party applications are located in the utils folder. You can add your own by placing them in `$HOME/.config/util/setup`. Calling the setup script in your shell configuration result in the files at `$HOME/.config/util/setup` being automatically loaded.

Custom completions can be set as comments after a `# Completions` comment header. See `$HOME/.config/util/scripts/locale/gettext.sh` for reference.

Help sections can be added as a text after a comment `# help: `. See `$HOME/.config/util/scripts/update.sh` for reference.

.SH OPTIONS
.TP
.B \-\-help
Show help information for the `util` command.

.SH EXAMPLES
.TP
.B util update
Executes a script named `update.sh` in `$HOME/.config/util/scripts`.

.TP
.B util git checkout-pr
Executes a script named `checkout-pr.sh` in `$HOME/.config/util/scripts/git`.

.TP
.B util config add-script-folder <folder> <destination_name>
Creates symbolic links for the folder at <folder> in `$HOME/.config/util/scripts/<destination_name>`. The scripts are now accessbile via `$ util <folder> path to script`.

The recommended way of configuring the scripts is manually copying/stowing them to `$HOME/.config/util/scripts` following the structure which best fit your needs. This command just facilitates the process.

.TP
.B util config remove-script-folder <folder>
Removes the symbolic links for the folder at `$HOME/.config/util/<folder>`

.SH AUTHOR
Written by vncsmyrnk.
.SH SEE ALSO
Visit https://github.com/vncsmyrnk/shell-utils for more information.
