.TH util 1 "October 2025" "shell-utils" "User Commands"
.SH NAME
util \- A shell-agnostic utility tool for managing user scripts
.SH SYNOPSIS
.B util
[\-\-help] [arguments]
.SH DESCRIPTION
.B util
is a shell-agnostic utility tool designed to make your scripts accessible everywhere using the `util` command.

All the arguments represent the path to script to be executed from `$HOME/.config/util/scripts` without directory separators, like a CLI application. Additional arguments after the path is matched are seamlessly passed to the specified script.

Setup scripts for third-party applications are located in the utils folder. You can add your own by placing them in `$HOME/.config/util/setup`. Calling the setup script in your shell configuration result in the files at `$HOME/.config/util/setup` being automatically loaded.

Custom completions can be set as comments after a `# Completions` comment header. See `$HOME/.config/util/scripts/locale/gettext.sh` for reference.

Help sections can be added as a text after a comment `# help: `. See `$HOME/.config/util/scripts/update.sh` for reference. Multi-line texts are suported. All commented lines after the `help` header will be considered a part of the help section.

If an uncompleted but existing path to a command was given (a directory was found but not a script) the available scripts at the input path will be listed in a "commands available" section. A custom help section can be put inside a directory named `help` will be printed along the default "commands available" section. The help file content is printed using `printf` so it supports cutomization like text coloring.

The "commands available" section will list only the summarized help section of each script available (i.e. the first line of the `help` comment).

.SS Extra scripts

The objective of the `util` command is to provide a way to call your own custom scripts, but it also has a couple of useful ones.

They are called "extra scripts", useful for daily activies. Backup and update are good examples.

.SH OPTIONS
.TP
.B \-\-help
Show help information for the `util` command.

.SH EXAMPLES
.TP
.B util update
Executes a script named `update.sh` in `$HOME/.config/util/scripts`.

.TP
.B util git checkout-pr
Executes a script named `checkout-pr.sh` in `$HOME/.config/util/scripts/git`.

.TP
.B util config add-script-folder <folder> <destination_name>
Creates symbolic links for the folder at <folder> in `$HOME/.config/util/scripts/<destination_name>`. The scripts are now accessbile via `$ util <folder> path to script`.

The recommended way of configuring the scripts is manually copying/stowing them to `$HOME/.config/util/scripts` following the structure which best fit your needs. This command just facilitates the process.

.TP
.B util config remove-script-folder <folder>
Removes the symbolic links for the folder at `$HOME/.config/util/<folder>`

.SH AUTHOR
Written by vncsmyrnk.
.SH SEE ALSO
Visit https://github.com/vncsmyrnk/shell-utils for more information.
