//go:build ignore

package main

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const tmpl = `// Code generated by gen_router.go. DO NOT EDIT.
package main

var Router = map[string]string{
{{- range $key, $path := . }}
	"{{ $key }}": "{{ $path }}",
{{- end }}
}
`

func main() {
	scriptsDir := "../../scripts"
	if len(os.Args) >= 2 {
		scriptsDir = os.Args[1]
	}

	routes := make(map[string]string)
	err := filepath.WalkDir(scriptsDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil || strings.HasPrefix(d.Name(), "_") || d.Name() == "help" {
			return nil
		}

		pRel, err := filepath.Rel(scriptsDir, path)
		if err != nil {
			return nil
		}

		parts := strings.Split(filepath.ToSlash(pRel), "/")
		if len(parts) < 1 {
			return nil
		}

		if !d.IsDir() {
			lastIdx := len(parts) - 1
			filename := parts[lastIdx]
			parts[lastIdx] = strings.TrimSuffix(filename, filepath.Ext(filename))
		}

		var aliasMatrix [][]string
		for _, part := range parts {
			aliases := strings.Split(part, ".")
			aliasMatrix = append(aliasMatrix, aliases)
		}

		generatedRoutes := generatePermutations(aliasMatrix)
		for _, routeKey := range generatedRoutes {
			routes[routeKey] = pRel
		}

		return nil
	})

	if err != nil {
		fmt.Fprintf(os.Stderr, "Error walking scripts: %v\n", err)
		os.Exit(1)
	}

	f, err := os.Create("router_generated.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating generated file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	t := template.Must(template.New("router").Parse(tmpl))
	if err := t.Execute(f, routes); err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}
}

// generatePermutations recursively builds a Cartesian product of all aliases
func generatePermutations(matrix [][]string) []string {
	if len(matrix) == 0 {
		return nil
	}
	// Base case: we are at the last element (the file)
	if len(matrix) == 1 {
		return matrix[0]
	}

	var result []string
	// Get all permutations of the sub-directories/files
	tails := generatePermutations(matrix[1:])

	// Cross the current aliases with the tail permutations
	for _, head := range matrix[0] {
		for _, tail := range tails {
			result = append(result, head+":"+tail)
		}
	}
	return result
}
