name: CI/CD workflow

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check flake
        run: nix flake check

      - name: Build flake
        run: make buildflake

  ci-pkgbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Arch Package
        uses: edlanglois/pkgbuild-action@v1
        with:
          namcap: true

  ci-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Install packaging dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ruby ruby-dev rubygems build-essential
          sudo gem install fpm

      - name: Build DEB
        run: make deb

      - name: Archive artifacts
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: ./**/*.deb

  cd-check:
    needs: [ci, ci-deb, ci-pkgbuild]
    runs-on: ubuntu-latest
    outputs:
      pkgbuild-changed: ${{ steps.filter.outputs.pkgbuild-changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for PKGBUILD version change
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            pkgbuild-changed:
              - 'PKGBUILD'

  cd-pkgbuild:
    needs: [cd-check]
    if: ${{ needs.cd-check.outputs.pkgbuild-changed == 'true' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip-cd]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.3
        with:
          pkgname: shell-utils-git
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update AUR package"
          ssh_keyscan_types: rsa,ecdsa,ed25519

  cd-apt:
    needs: [cd-check]
    if: ${{ github.ref_type == 'tag' && !contains(github.event.head_commit.message, '[skip-cd]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deb

      - name: Upload to Gemfury
        run: |
          DEB_FILE=$(find . -name '*.deb' -type f | head -n 1)
          curl -F package=@$DEB_FILE https://${{ secrets.GEMFURY_PUSH_TOKEN }}@push.fury.io/vncsmyrnk
